/** Actionable DeFi trading tips — combined uniquely per page by seed + tip number. */
export const TRADING_TIPS: readonly string[] = [
  "Set slippage from pool depth, not habit — 0.5% for deep stablecoin pairs, higher only when quotes fail.",
  "Compare minimum received across two routes before signing large trades.",
  "Keep a separate native-gas buffer; never spend your last ETH/SOL/BNB on the swap itself.",
  "Verify token contracts on the official explorer — tickers lie, addresses do not.",
  "Revoke unlimited ERC-20 approvals you no longer use.",
  "Re-quote if more than sixty seconds pass between preview and signature.",
  "Split orders when price impact exceeds one to two percent.",
  "Use stablecoin legs for simpler profit-and-loss tracking.",
  "Bookmark the official site URL; ignore sponsored ads with similar names.",
  "Run a small test trade before sizing up on new tokens.",
  "Read the full route path — multi-hop quotes can hide thin intermediate pools.",
  "During volatility, widen slippage incrementally, never jump to maximum.",
  "Check Discover liquidity before aping into trending tokens.",
  "Confirm wallet network matches the chain selector before approving.",
  "Export transaction hashes for tax records — aggregators do not file for you.",
  "Avoid copying contract addresses from social media threads.",
  "Prefer exact token allowances over infinite approvals when your wallet supports them.",
  "Watch for fee-on-transfer tokens that deliver less than quoted.",
  "Bridge with a test amount first on routes you have not used before.",
  "Budget gas on both source and destination chains for cross-chain moves.",
  "Do not resubmit bridge transactions while the first is still in transit.",
  "Stablecoin spreads should be tight — investigate unusual deviations.",
  "Memecoin liquidity can vanish in minutes; size accordingly.",
  "Limit orders and spot swaps behave differently — know which you are using.",
  "Priority fees on Solana help during congested mints.",
  "Replace stuck EVM transactions with the same nonce instead of stacking pending txs.",
  "Sandwich bots target high slippage — tight settings reduce exposure on public mempools.",
  "Wrapped BTC and native BTC representations differ — confirm which you hold.",
  "Bridged USDC variants are not always fungible across protocols.",
  "Read launchpad contract permissions (mint, pause, blacklist) before buying.",
  "Liquidity locks reduce but do not eliminate rug risk.",
  "Holder concentration on explorers signals distribution risk for new tokens.",
  "Weekend liquidity is often thinner — expect wider spreads.",
  "L2 gas is cheaper but bridged asset liquidity may be thinner than mainnet.",
  "Paying platform fees in USDC reduces native-token dust if you already hold stables.",
  "Simulation failures usually mean size too large or slippage too tight.",
  "Never share seed phrases with anyone claiming to be support.",
  "Hardware wallets add friction that prevents impulsive approvals.",
  "Use a dedicated hot wallet for experimental DeFi, not your long-term vault.",
  "Correlated ecosystem tokens may share venues — compare routes anyway.",
  "Chart spikes without volume often mean wash trading, not real depth.",
  "Oracle delays can widen spreads briefly after large external moves.",
  "MEV protection features vary by chain — understand what your route actually uses.",
  "Tax treatment of swaps varies by country — consult a professional if unsure.",
  "Accounting in USDC simplifies reporting even when you trade altcoins.",
  "Token migrations require you to swap old contracts before liquidity moves.",
  "Airdrop phishing uses fake claim sites — verify URLs from official channels only.",
  "Typed data signatures can drain wallets — read what you sign.",
  "Blind signing on unknown dApps is a common wallet-drainer vector.",
  "Keep browser extensions updated; malicious extensions swap clipboard addresses.",
  "Two-factor authentication on CEX accounts does not protect on-chain keys.",
  "Cold storage for savings, hot wallet for trading — separate concerns.",
  "Document your cost basis at acquisition, not only at sale.",
  "Failed transactions still burn gas on most EVM networks.",
  "Batch approvals when gas is high, but revoke what you no longer need.",
  "Native coin pairs usually have the tightest spreads on each network.",
  "Routing through WETH or USDC hops is normal — inspect each hop's impact.",
  "Aggregator fees are explicit in the quote card — network gas is separate.",
  "Do not chase green candles without checking pool age and lock status.",
  "Volume on one DEX does not guarantee depth on another for the same ticker.",
  "Cross-chain arbitrage sounds easy; bridge time and fees often erase edge.",
  "Relayer outages happen — check bridge status pages during delays.",
  "Destination-chain congestion can delay the final leg after bridging.",
  "Auto-slippage tools exist but manual review still catches bad routes.",
  "Wallet connect sessions expire — reconnect before large trades.",
  "Mobile wallets work, but confirm you are on the correct chain in app settings.",
  "QR codes for addresses should be scanned, not typed from screenshots.",
  "Phishing sites mimic UI pixels — verify SSL and domain character-by-character.",
  "Community Telegram 'support' DMs are almost always scams.",
  "No legitimate project asks you to approve tokens to 'fix' your wallet.",
  "Dust tokens sent to your wallet may be honeypots — do not interact.",
  "Reading pool reserves on explorers helps estimate impact before quoting.",
  "Concentrated liquidity pools behave differently from full-range V2 pools.",
  "Impermanent loss matters for LPs, not spot swappers — but know the difference.",
  "Governance tokens may have low float early — expect volatility.",
  "Staking derivatives carry smart-contract risk beyond the underlying asset.",
  "Restaking narratives change quickly — liquidity can exit fast.",
  "Points programs incentivize volume, not necessarily good trades for you.",
  "Backtest ideas with small size on mainnet rather than assuming backtested APY.",
  "RPC endpoints affect simulation speed — slow RPCs delay quotes.",
  "Private RPCs reduce some MEV exposure but do not eliminate contract risk.",
  "Indexers lag during chain stress — re-quote before signing large trades.",
  "Discover trends show activity, not investment merit.",
  "Launchpad listings are not endorsements — do your own contract review.",
  "Fair launch means different things — read the actual deployment parameters.",
  "Team allocations visible on explorers deserve scrutiny on new tokens.",
  "Vesting cliffs create supply shocks — plan exits around unlock calendars.",
  "Pair creation bots spam new pools — verify factory contract on official docs.",
  "Honeypot tokens block sells — simulation failures can be a warning sign.",
  "Tax tokens deduct on transfer — quotes may not match wallet receipt.",
  "Rebasing tokens break some integrations — check compatibility.",
  "NFT-floor sweeps and token trades share wallets — segregate if possible.",
  "Approve-and-revoke patterns reduce lingering attack surface.",
  "Session keys and account abstraction change approval models — read prompts.",
  "Multi-sig treasuries reduce single-key risk for project funds.",
  "Oracle manipulation attacks target thin pools — size down on obscure pairs.",
  "Flash-loan attacks on protocols rarely help retail traders — ignore hype.",
  "Insurance protocols exist but read exclusions before relying on them.",
  "Stable depeg events require pausing, not averaging down blindly.",
  "Algorithmic stables history suggests caution — understand redemption mechanics.",
  "CBDCs and on-chain stables are different products — do not conflate them.",
  "Fiat ramps and DEX swaps have different KYC surfaces — plan accordingly.",
  "OTC desks solve size but introduce counterparty risk aggregators remove.",
  "Peer-to-peer trades need escrow or reputation — on-chain pools do not.",
  "Limit order protocols may charge different fees than spot aggregators.",
  "Stop-loss on-chain is not universal — know whether your tool supports it.",
  "Trailing stops on DEXs are rare — manual discipline still matters.",
  "Calendar reminders to revoke approvals quarterly reduce long-tail risk.",
  "Spreadsheet tracking beats memory for active traders across chains.",
  "Label wallets by purpose in your address book to prevent wrong-chain sends.",
  "Test recipient addresses with a micro-send before large transfers.",
  "Memo/tag fields on CEX deposits do not apply to EVM — do not confuse models.",
  "Checksum addresses reduce typo risk — use them in wallets that support it.",
  "ENS names resolve to addresses — verify resolution before sending.",
  "Contract upgradeability means rules can change — read proxy patterns.",
  "Timelocks on admin functions give users exit time — check if present.",
  "Multichain portfolio trackers aggregate balances but not risk.",
  "Yield and swap platforms differ — do not assume APY applies to spot trades.",
  "Leverage perps are separate products from spot swaps — stay in the right UI mode.",
  "Liquidation risk does not apply to spot swaps — confusion causes mistakes.",
  "Borrowing against crypto to swap more is a different risk class entirely.",
  "Dollar-cost averaging works better with planned sizes than reactive chasing.",
  "Rebalancing quarterly beats daily tinkering for most portfolios.",
  "Correlation spikes in crashes — diversification within crypto is limited.",
  "Stablecoin parking between trades reduces volatility exposure between legs.",
  "Gas tokens and meta-transactions can simplify UX but add contract layers.",
  "Paymasters on L2s subsidize gas — understand who pays long term.",
  "Account abstraction wallets may batch actions — review the full batch.",
  "Intent-based systems quote outcomes — still verify minimum received.",
  "Solver competition improves prices — compare intent solvers when available.",
  "Cross-chain intents add relayer trust — read provider reputation.",
  "Wormhole, LayerZero, and native bridges differ in trust assumptions.",
  "Canonical bridges from official docs beat unofficial Telegram links.",
  "Wrapped native on L2 is still native for gas — but bridged assets may differ.",
  "Native yield on staked ETH products is not the same as ETH spot price exposure.",
  "LST tokens carry peg and smart-contract risk relative to ETH.",
  "Restaked LSTs stack risks — read the stack, not just headline yield.",
  "MEV refunds vary — do not treat them as guaranteed income.",
  "Private mempools on some chains change fairness properties — know your chain.",
  "Block builders reorder txs — slippage limits are your main retail defense.",
  "Flashbots protect some flows — not all aggregators route through them.",
  "Wallet simulation previews failures — use them before confirming.",
  "Tenderly-style traces help debug failed txs for developers and power users.",
  "Nonce gaps on EVM can block later txs until filled — monitor pending queue.",
  "Cancel transactions by sending zero-value self-tx with same nonce and higher gas.",
  "Layer hops for tax reporting may create multiple taxable events.",
  "Gift and donation transfers still need correct addresses and chains.",
  "Charity scams use disaster headlines — verify org wallets independently.",
  "Rug pull red flags include unlocked LP, mintable supply, and anonymous teams.",
  "Audits help but are not guarantees — read scope and date.",
  "Bug bounties signal maturity — absence does not always mean danger, but weigh it.",
  "Community size can be bot-inflated — focus on developer activity and liquidity.",
  "GitHub commits can be faked — liquidity and contract immutability matter more.",
  "Token snipers on launches hurt retail — expect bad fills in block zero.",
  "Anti-bot launch mechanics may still fail — assume early volatility.",
  "Whitelist launches reduce bot competition but centralize allocation.",
  "Dutch auctions price discovery differs from fixed-price launches.",
  "Bonding curves reward early entrants disproportionately — model your entry.",
  "LP seeding at launch sets initial price — check seed size versus float.",
  "Lock duration on LP tokens should match your holding horizon if you LP.",
  "V2 versus V3 LP mechanics differ — concentrated ranges need active management.",
  "IL calculators estimate LP risk — spot traders can ignore IL but should know it exists.",
  "Pool fees accrue to LPs, not swappers — you pay them on each swap.",
  "Fee tiers on V3 pools affect which pool aggregators pick.",
  "Tick spacing changes price granularity on concentrated pools.",
  "Oracle TWAPs resist manipulation over time but lag spot.",
  "Spot price and TWAP diverge in crashes — limit orders using TWAP react slowly.",
  "Governance votes can change fee switches — monitor if you LP long term.",
  "Protocol treasuries dumping tokens affects price — watch governance forums.",
  "Emission schedules create sell pressure — map unlocks against your trades.",
  "Buyback narratives need on-chain proof, not slide decks.",
  "Revenue-sharing tokens tie value to protocol fees — verify fee switch is on.",
  "Real yield versus emissions differs — read whether rewards are minted or paid.",
  "Points farming ends — liquidity often exits when programs stop.",
  "Airdrop eligibility rumors cause sybil behavior — trade for edge, not gossip.",
  "Wallet clustering analytics exist — privacy is limited on public chains.",
  "Mixers and privacy tools carry legal and security risks — understand jurisdiction.",
  "Cross-chain privacy is harder than single-chain — plan accordingly.",
  "Regulatory news moves stablecoin flows — expect bridge congestion after headlines.",
  "Bank holidays affect fiat ramps, not on-chain pools — plan cash movements.",
  "Timezone liquidity patterns exist — US/EU hours often tighten spreads.",
  "Asia session opens can move memecoins born on local social channels.",
  "Macro news hits BTC and ETH first — altcoins follow with lag and amplification.",
  "Correlation to BTC rises in drawdowns — diversification assumptions break.",
  "Stablecoin depegs during bank stress — keep multiple stables only if you understand each.",
  "On-chain proof of reserves for CEXs differs from DEX pool reserves.",
  "Proof-of-reserve attestations expire — check dates.",
  "Self-custody means no chargebacks — every send is final.",
  "Support tickets cannot reverse blockchain txs — prevention beats recovery.",
  "Insurance on custodial platforms does not cover self-custody mistakes.",
  "Education beats leverage for long-term survival in volatile markets.",
];

export function isTradingTipPage(h1: string): boolean {
  return /^DeFi trading tip \d+$/i.test(h1);
}

export function tipNumber(h1: string): number {
  return parseInt(h1.match(/\d+/)?.[0] ?? "1", 10);
}
